[package]
name = "silero-rs"
version = "0.1.0"
edition = "2021"
description = "Rust bindings for silero's C++ wrapper"
license = "Unlicense"
documentation = "https://docs.rs/sileror-rs"
repository = "https://github.com/Infoserv-Systems-Ltd/sileror-rs"

[dependencies]
onnxruntime = "0.0.14"
ort = "1.16.3"
rand = "0.8.5"
rodio = "0.17.3"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
