name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: setup
        run: sudo usermod -aG docker $USER
      - name: linux_version
        run: lsb_release -a
      - name: Build
        run: ORT_STRATEGY=system ORT_LIB_LOCATION=.github/workflows cargo build --verbose 
      - name: Run tests
        run: 
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.github/workflows
          ORT_STRATEGY=system ORT_LIB_LOCATION=.github/workflows cargo test