name: Rust

on:
  push:
    branches: ["main", "increase-test-coverage"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: setup
        run: sudo usermod -aG docker $USER

      - name: linux_version
        run: lsb_release -a

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
        env:
          LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:.github/workflows"
          ORT_STRATEGY: "system"
          ORT_LIB_LOCATION: ".github/workflows"

      - name: Clean workspace
        uses: actions-rs/cargo@v1
        with:
          command: clean

      - name: Print Current Working Directory
        run: pwd

      - name: Print LD_LIBRARY_PATH
        run: echo $LD_LIBRARY_PATH

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast # Customize args for your own needs
        env:
          LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:.github/workflows"
          ORT_STRATEGY: "system"
          ORT_LIB_LOCATION: ".github/workflows"
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-C instrument-coverage"
          LLVM_PROFILE_FILE: "silero.profraw"
          # RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cllvm-args=--inline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"
          # RUSTDOCFLAGS: "-Zprofile -Ccodegen-units=1 -Cllvm-args=--inline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"

      - name: Report Test Coverage
        id: coverage
        uses: actions-rs/grcov@v0.1

      - name: Coveralls upload
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: ${{ steps.coverage.outputs.report }}

      # - name: Run tests
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: llvm-cov
      #   env:
      #     LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:.github/workflows"
      #     ORT_STRATEGY: "system"
      #     ORT_LIB_LOCATION: ".github/workflows"
      #     RUSTFLAGS: "-C instrument-coverage"
      #     LLVM_PROFILE_FILE: "silero.profraw"
