name: Rust

on:
  push:
    branches: ["main", "increase-test-coverage"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.77.2
          override: true

      - name: setup
        run: sudo usermod -aG docker $USER

      - name: linux_version
        run: lsb_release -a

      - name: Build
        run: |
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.github/workflows \
            ORT_STRATEGY=system \
            ORT_LIB_LOCATION=.github/workflows \
            cargo build

      - name: Install LLVM Tools
        run: cargo +stable install cargo-llvm-cov --locked

      - name: Run tests
        run: |
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.github/workflows \
            ORT_STRATEGY=system \
            ORT_LIB_LOCATION=.github/workflows \
            RUSTFLAGS="-C instrument-coverage" \
            LLVM_PROFILE_FILE="silero.profraw" \
            cargo test
